server:
  port: 8082

spring:
  application:
    name: FILE-SERVICE

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=VHL;encrypt=true;trustServerCertificate=true
    username: sa
    password: A_bc1234!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 2GB        
      max-request-size: 2GB     

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: file-bucket
